# Generated by Django 5.2.8 on 2025-12-13 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("exams", "0001_initial"),
        ("orders", "0001_initial"),
        ("patients", "0001_initial"),
        ("pricing", "0001_initial"),
        ("referrals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="pricing.coupon",
                verbose_name="Coupon",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="orders", to="patients.patient"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="referral",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="referrals.referral",
                verbose_name="Referral",
            ),
        ),
        migrations.AddField(
            model_name="orderdetail",
            name="exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="order_details", to="exams.exam"
            ),
        ),
        migrations.AddField(
            model_name="orderdetail",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="details", to="orders.order"
            ),
        ),
    ]
