# Generated by Django 5.2.8 on 2025-11-27 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
        ("pricing", "0001_initial"),
        ("referrals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="pricing.coupon",
                verbose_name="Coupon",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="referral",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="referrals.referral",
                verbose_name="Referral",
            ),
        ),
    ]
