# Generated by Django 5.2.8 on 2025-12-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_change_order_status_values"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="observations",
            field=models.TextField(blank=True, default="", verbose_name="Observaciones"),
        ),
    ]
