# Generated by Django 5.2.8 on 2025-12-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cash", "Efectivo"),
                    ("bank_transfer", "Transferencia bancaria"),
                    ("card", "Tarjeta"),
                    ("digital_wallet", "Billeteras digitales"),
                ],
                max_length=20,
                null=True,
                verbose_name="Método de Pago",
            ),
        ),
    ]
