# Generated by Django 5.2.16 on 2026-10-10 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_payment"),
        ("quotes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="quote",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order",
                to="quotes.quote",
                verbose_name="Cotización",
            ),
        ),
    ]
