# Generated by Django 5.2.8 on 2025-11-27 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("pricing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Referral",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("business_name", models.CharField(max_length=200, verbose_name="Business Name")),
                ("document_number", models.CharField(max_length=11, unique=True, verbose_name="RUC")),
                ("phone_number", models.CharField(blank=True, max_length=20, verbose_name="Phone Number")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="Email")),
                ("address", models.TextField(blank=True, verbose_name="Address")),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "price_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="referrals",
                        to="pricing.pricelist",
                        verbose_name="Price List",
                    ),
                ),
            ],
            options={
                "verbose_name": "Referral",
                "verbose_name_plural": "Referrals",
            },
        ),
    ]
