# Generated by Django 5.2.8 on 2025-11-25 22:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("business_name", models.CharField(max_length=200, verbose_name="Razon Social")),
                ("document_number", models.CharField(max_length=11, unique=True, verbose_name="RUC")),
                ("phone_number", models.CharField(max_length=20, verbose_name="Telefono")),
                ("email", models.EmailField(max_length=254, verbose_name="Correo Electronico")),
                ("legal_address", models.TextField(verbose_name="Direccion Legal")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Fecha de Creacion")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Fecha de Actualizacion")),
            ],
            options={
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresa",
            },
        ),
    ]
