# Generated by Django 5.2.16 on 2026-10-10 02:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("exams", "0002_make_category_optional"),
        ("pricing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Fecha de Creacion")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Fecha de Actualizacion")),
                (
                    "code",
                    models.CharField(editable=False, max_length=20, unique=True, verbose_name="Código de Cotización"),
                ),
                ("observations", models.TextField(blank=True, default="", verbose_name="Observaciones")),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pendiente"), ("converted", "Convertida")],
                        default="pending",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "coupon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotes",
                        to="pricing.coupon",
                        verbose_name="Cupón",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cotización",
                "verbose_name_plural": "Cotizaciones",
            },
        ),
        migrations.CreateModel(
            name="QuoteDetail",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Precio")),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quote_details",
                        to="exams.exam",
                        verbose_name="Examen",
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="quotes.quote",
                        verbose_name="Cotización",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Cotización",
                "verbose_name_plural": "Detalles de Cotización",
            },
        ),
    ]
