# Generated by Django 5.2.8 on 2025-11-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "document_type",
                    models.CharField(
                        choices=[("DNI", "DNI"), ("CE", "Carnet de Extranjería"), ("PASAPORTE", "Pasaporte")],
                        default="DNI",
                        max_length=20,
                    ),
                ),
                ("document_number", models.CharField(max_length=20, unique=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("birthdate", models.DateField()),
                ("gender", models.CharField(choices=[("MALE", "Hombre"), ("FEMALE", "Mujer")], max_length=10)),
                ("phone", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Patient",
                "verbose_name_plural": "Patients",
            },
        ),
    ]
