# Generated by Django 5.2.8 on 2025-11-25 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LeadSource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="Nombre")),
                ("description", models.TextField(blank=True, verbose_name="Descripción")),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                ("order", models.PositiveIntegerField(default=0, help_text="Orden de visualización")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Canal de Adquisición",
                "verbose_name_plural": "Canales de Adquisición",
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "document_type",
                    models.CharField(
                        choices=[("DNI", "DNI"), ("CE", "Carnet de Extranjería"), ("PASAPORTE", "Pasaporte")],
                        default="DNI",
                        max_length=20,
                    ),
                ),
                ("document_number", models.CharField(max_length=20, unique=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("birthdate", models.DateField()),
                ("sex", models.CharField(choices=[("MALE", "Masculino"), ("FEMALE", "Femenino")], max_length=10)),
                ("phone_number", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lead_source",
                    models.ForeignKey(
                        blank=True,
                        help_text="Canal por el cual el cliente llegó por primera vez",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="patients.leadsource",
                        verbose_name="¿Cómo nos conoció?",
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient",
                "verbose_name_plural": "Patients",
            },
        ),
    ]
