# Generated by Django 5.2.8 on 2025-11-28 23:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leadsource",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Fecha de Creacion"),
        ),
        migrations.AlterField(
            model_name="leadsource",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Fecha de Actualizacion"),
        ),
        migrations.AlterField(
            model_name="patient",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Fecha de Creacion"),
        ),
        migrations.AlterField(
            model_name="patient",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Fecha de Actualizacion"),
        ),
    ]
