# Generated by Django 5.2.8 on 2025-12-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="presumptive_diagnosis",
            field=models.TextField(blank=True, default="", verbose_name="Presunción Médica"),
        ),
    ]
