# Generated by Django 5.2.8 on 2025-12-13 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExamCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Fecha de Creacion")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Fecha de Actualizacion")),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "Exam Category",
                "verbose_name_plural": "Exam Categories",
            },
        ),
        migrations.CreateModel(
            name="Provider",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Fecha de Creacion")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Fecha de Actualizacion")),
                ("name", models.CharField(max_length=200, unique=True)),
                ("contact_name", models.CharField(blank=True, max_length=200)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Provider",
                "verbose_name_plural": "Providers",
            },
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Fecha de Creacion")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Fecha de Actualizacion")),
                ("code", models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "has_components",
                    models.BooleanField(
                        default=False, help_text="Marcar si este examen contiene otros exámenes (ej: perfiles, paneles)"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="exams", to="exams.examcategory"
                    ),
                ),
            ],
            options={
                "verbose_name": "Exam",
                "verbose_name_plural": "Exams",
            },
        ),
        migrations.CreateModel(
            name="ExamComponent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Fecha de Creacion")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Fecha de Actualizacion")),
                ("order", models.PositiveIntegerField(default=0, help_text="Orden de aparición en el panel")),
                (
                    "component_exam",
                    models.ForeignKey(
                        help_text="Examen componente",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="included_in_panels",
                        to="exams.exam",
                    ),
                ),
                (
                    "parent_exam",
                    models.ForeignKey(
                        help_text="Examen padre (panel)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="component_items",
                        to="exams.exam",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exam Component",
                "verbose_name_plural": "Exam Components",
                "unique_together": {("parent_exam", "component_exam")},
            },
        ),
        migrations.AddField(
            model_name="exam",
            name="components",
            field=models.ManyToManyField(
                blank=True,
                related_name="parent_exams",
                through="exams.ExamComponent",
                through_fields=("parent_exam", "component_exam"),
                to="exams.exam",
            ),
        ),
        migrations.CreateModel(
            name="Methodology",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Fecha de Creacion")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Fecha de Actualizacion")),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "exam",
                    models.ForeignKey(
                        blank=True,
                        help_text="Examen al que pertenece esta metodología",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="methodologies",
                        to="exams.exam",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        help_text="Proveedor externo si el examen se terceriza",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="methodologies",
                        to="exams.provider",
                    ),
                ),
            ],
            options={
                "verbose_name": "Methodology",
                "verbose_name_plural": "Methodologies",
                "unique_together": {("name", "exam")},
            },
        ),
    ]
