# Generated by Django 5.2.8 on 2025-11-16 22:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="code",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
