# Generated by Django 5.2.8 on 2025-11-30 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0002_alter_exam_created_at_alter_exam_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Fecha de Creacion")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Fecha de Actualizacion")),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "Exam Category",
                "verbose_name_plural": "Exam Categories",
            },
        ),
        migrations.AddField(
            model_name="exam",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="exams",
                to="exams.examcategory",
            ),
        ),
    ]
