# Generated by Django 5.2.8 on 2025-12-03 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0003_examcategory_exam_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Methodology",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Fecha de Creacion")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Fecha de Actualizacion")),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Methodology",
                "verbose_name_plural": "Methodologies",
            },
        ),
        migrations.CreateModel(
            name="Provider",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Fecha de Creacion")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Fecha de Actualizacion")),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("contact_name", models.CharField(blank=True, max_length=200)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Provider",
                "verbose_name_plural": "Providers",
            },
        ),
        migrations.AddField(
            model_name="exam",
            name="has_components",
            field=models.BooleanField(
                default=False, help_text="Marcar si este examen contiene otros exámenes (ej: perfiles, paneles)"
            ),
        ),
        migrations.CreateModel(
            name="ExamComponent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Fecha de Creacion")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Fecha de Actualizacion")),
                ("order", models.PositiveIntegerField(default=0, help_text="Orden de aparición en el panel")),
                (
                    "component_exam",
                    models.ForeignKey(
                        help_text="Examen componente",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="included_in_panels",
                        to="exams.exam",
                    ),
                ),
                (
                    "parent_exam",
                    models.ForeignKey(
                        help_text="Examen padre (panel)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="component_items",
                        to="exams.exam",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exam Component",
                "verbose_name_plural": "Exam Components",
                "unique_together": {("parent_exam", "component_exam")},
            },
        ),
        migrations.AddField(
            model_name="exam",
            name="components",
            field=models.ManyToManyField(
                blank=True,
                related_name="parent_exams",
                through="exams.ExamComponent",
                through_fields=("parent_exam", "component_exam"),
                to="exams.exam",
            ),
        ),
        migrations.CreateModel(
            name="ExamMethodology",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Fecha de Creacion")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Fecha de Actualizacion")),
                (
                    "is_default",
                    models.BooleanField(default=False, help_text="Metodología por defecto para este examen"),
                ),
                (
                    "price_adjustment",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Ajuste sobre el precio base del examen (puede ser positivo o negativo)",
                        max_digits=10,
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="exam_methodologies", to="exams.exam"
                    ),
                ),
                (
                    "methodology",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exam_methodologies",
                        to="exams.methodology",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exam Methodology",
                "verbose_name_plural": "Exam Methodologies",
                "unique_together": {("exam", "methodology")},
            },
        ),
        migrations.AddField(
            model_name="exam",
            name="methodologies",
            field=models.ManyToManyField(
                blank=True, related_name="exams", through="exams.ExamMethodology", to="exams.methodology"
            ),
        ),
        migrations.AddField(
            model_name="methodology",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                help_text="Proveedor externo si el examen se terceriza",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="methodologies",
                to="exams.provider",
            ),
        ),
    ]
