# Generated by Django 5.2.8 on 2025-12-04 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0004_methodology_provider_exam_has_components_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exam",
            name="methodologies",
        ),
        migrations.AddField(
            model_name="methodology",
            name="exam",
            field=models.ForeignKey(
                blank=True,
                help_text="Examen al que pertenece esta metodología",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="methodologies",
                to="exams.exam",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="methodology",
            unique_together={("exam", "code")},
        ),
        migrations.DeleteModel(
            name="ExamMethodology",
        ),
    ]
