# Generated by Django 5.2.8 on 2025-12-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0005_remove_exam_methodologies_methodology_exam_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="methodology",
            unique_together={("name", "exam")},
        ),
        migrations.RemoveField(
            model_name="provider",
            name="code",
        ),
        migrations.AlterField(
            model_name="provider",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.RemoveField(
            model_name="methodology",
            name="code",
        ),
    ]
