# Generated by Django 5.2.8 on 2025-11-16 22:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admissions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pendiente"), ("completed", "Completada"), ("cancelled", "Cancelada")],
                default="completed",
                max_length=20,
            ),
        ),
    ]
