# Generated by Django 5.2.8 on 2025-11-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="gender",
            field=models.CharField(choices=[("MALE", "Hombre"), ("FEMALE", "Mujer")], max_length=10),
        ),
    ]
